apiVersion: v1
kind: ResourceQuota
metadata:
  name: timestamp-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: "10"
    requests.cpu: "300m"
    requests.memory: "192Mi"
    limits.cpu: "1200m"
    limits.memory: "320Mi"
