apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-formatter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-formatter
  template:
    metadata:
      labels:
        app: timestamp-formatter
    spec:
      containers:
        - name: timestamp-formatter
          image: karslo92111/timestamp-formatter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /_/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /_/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: GENERATOR_SERVICE_URL
              value: "http://timestamp-generator:8080"
