apiVersion: v1
kind: Service
metadata:
  name: timestamp-formatter
spec:
  type: NodePort
  selector:
    app: timestamp-formatter
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
